version: '3.1'

services:
 web:
  build:
   context: .
  ports:
    - 8000:5000
  volumes:
    - ./:/app
    - raw_data:/raw_data

 mongo:
   image: mongo
   restart: always
   environment:
     MONGO_INITDB_ROOT_USERNAME: root
     MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  raw_data: 
    external: true
  mongo:
  mongo_config: